openapi: 3.0.0
info:
  title: FastAPI
  version: 0.1.3
paths:
  /users/:
    get:
      tags:
        - Users
      summary: Test Posts
      operationId: test_posts_users__get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/CreateUser'
                type: array
                title: Response Test Posts Users  Get
    post:
      tags:
        - Users
      summary: Test Posts Sent
      operationId: test_posts_sent_users__post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateUser'
        required: true
      responses:
        '201':
          description: Successful Response
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/CreateUser'
                type: array
                title: Response Test Posts Sent Users  Post
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /users/{id}:
    get:
      tags:
        - Users
      summary: Get Test One Post
      operationId: get_test_one_post_users__id__get
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            title: Id
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateUser'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
    delete:
      tags:
        - Users
      summary: Delete Test Post
      operationId: delete_test_post_users__id__delete
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            title: Id
      responses:
        '204':
          description: Successful Response
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /users/posts/{id}:
    put:
      tags:
        - Users
      summary: Update Test Post
      operationId: update_test_post_users_posts__id__put
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            title: Id
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /:
    get:
      summary: Root
      operationId: root__get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
  /mainScreen:
    get:
      summary: Mainscreen
      description: Returns info about user and tickets to redeem
      operationId: mainScreen_mainScreen_get
      parameters:
        - name: id
          in: query
          required: true
          schema:
            type: string
            title: Id
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /verify:
    post:
      summary: Verifyphoto
      description: Veryfies if photo and the selected bin are matching
      operationId: verifyPhoto_verify_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VerifyPhoto'
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VerifyPhotoResult'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /gemini:
    post:
      summary: Verifyphoto
      description: Veryfies if photo and the selected bin are matching
      operationId: verifyPhoto_gemini_post
      parameters:
        - name: user_id
          in: query
          required: true
          schema:
            type: string
            title: User Id
        - name: binTypeGuess
          in: query
          required: true
          schema:
            $ref: '#/components/schemas/Bin'
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Body_verifyPhoto_gemini_post'
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
components:
  schemas:
    Bin:
      type: string
      enum:
        - PAPER
        - GLASS
        - BIO
        - METAL_PLASTIC
        - MIXED
      title: Bin
    Body_verifyPhoto_gemini_post:
      properties:
        photo:
          type: string
          format: binary
          title: Photo
      type: object
      required:
        - photo
      title: Body_verifyPhoto_gemini_post
    CreateUser:
      properties:
        id:
          type: string
          title: Id
        score:
          type: integer
          title: Score
      type: object
      required:
        - id
        - score
      title: CreateUser
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          type: array
          title: Detail
      type: object
      title: HTTPValidationError
    User:
      properties:
        id:
          type: string
          title: Id
        score:
          type: integer
          title: Score
      type: object
      required:
        - id
        - score
      title: User
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
              - type: string
              - type: integer
          type: array
          title: Location
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type
      type: object
      required:
        - loc
        - msg
        - type
      title: ValidationError
    VerifyPhoto:
      properties:
        user_id:
          type: string
          title: User Id
          example: example@gmail.com
        binTypeGuess:
          $ref: '#/components/schemas/Bin'
        file:
          type: string
          title: File
      type: object
      required:
        - user_id
        - binTypeGuess
        - file
      title: VerifyPhoto
    VerifyPhotoPayload:
      properties:
        isBinTypeGuessCorrect:
          type: boolean
          title: Isbintypeguesscorrect
        pointsEarned:
          type: integer
          title: Pointsearned
          example: 2
        correctBinType:
          $ref: '#/components/schemas/Bin'
        notesFromAI:
          anyOf:
            - type: string
            - type: 'null'
          title: Notesfromai
          description: If wrong there will be an explanation why
          example: Oh no, your guess was wrong, you should use the PAPER bin.
      type: object
      required:
        - isBinTypeGuessCorrect
        - pointsEarned
        - correctBinType
      title: VerifyPhotoPayload
    VerifyPhotoResult:
      properties:
        status_code:
          type: integer
          title: Status Code
          example: 200
        payload:
          $ref: '#/components/schemas/VerifyPhotoPayload'
      type: object
      required:
        - status_code
        - payload
      title: VerifyPhotoResult
servers:
  # Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://ecosort-d4827d1603c3.herokuapp.com/